[icons]
icons = "awesome6"

[theme]
theme = "semi-native"
[theme.overrides]
separator = ""

[[block]]
block = "music"
[[block.click]]
action = "play_pause"
button = "left"

[[block]]
block = "net"
format = " $icon {$ssid |}$ip "
[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "

[[block]]
block = "cpu"

[[block]]
block = "load"

[[block]]
block = "battery"
interval = 10
format = "$icon $percentage $time"

[[block]]
block = "sound"
headphones_indicator=true
[[block.click]]
cmd = "pavucontrol"
button = "left"

[[block]]
block = "time"
interval = 60
format = "$icon $timestamp.datetime(f:'%a %Y-%m-%d %H:%M')"
