icons = "awesome"

[theme]
name = "native"

[[block]]
block = "music"
hide_when_empty = true
marquee = false
on_click = "playerctl play-pause"
dynamic_width = true

[[block]]
block = "networkmanager"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "%a %Y-%m-%d %H:%M"
